skip tests if docker is required but not available

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,9 +85,23 @@ jobs:
       - name: Install library
         run: poetry install --no-interaction
       #----------------------------------------------
-      #    run test suite
+      #    run test suite conditionally based on OS
       #----------------------------------------------
-      - name: Run tests
+      - name: Run tests on Ubuntu with Docker
+        if: matrix.os == 'ubuntu-latest'
         run: |
-          source $VENV
+          docker-compose up --build -d
           pytest tests/
+
+      # No Docker on Windows
+      - name: Run tests without Docker on Windows
+        if: matrix.os == 'windows-latest'
+        run: |
+          pytest -m "not docker_required" tests/
+      #----------------------------------------------
+      #    Cleanup step after running tests on Ubuntu
+      #----------------------------------------------
+      - name: Cleanup Docker containers and images
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          docker-compose down --volumes --remove-orphans || true
